version: "3"

services:
  nopaste:
    build: .
    restart: always
    ports:
      - 8080:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nopaste.rule=Host(`paste.server.com`)"
      - "treafik.http.routers.nopaste.entrypoints=websecure"
    networks:
      - web

networks:
  web:
    external: true
