const languages = {
    markup: 'Markup (HTML, XML, SVG)',
    css: 'CSS',
    clike: 'C-like',
    javascript: 'JavaScript',
    abap: 'ABAP',
    abnf: 'Augmented Backus–Naur form',
    actionscript: 'ActionScript',
    ada: 'Ada',
    antlr4: 'ANTLR4',
    apacheconf: 'Apache Configuration',
    apl: 'APL',
    applescript: 'AppleScript',
    aql: 'AQL',
    arduino: 'Arduino',
    arff: 'ARFF',
    asciidoc: 'AsciiDoc',
    asm6502: '6502 Assembly',
    aspnet: 'ASP.NET (C#)',
    autohotkey: 'AutoHotkey',
    autoit: 'AutoIt',
    bash: 'Bash',
    basic: 'BASIC',
    batch: 'Batch',
    bbcode: 'BBcode',
    bison: 'Bison',
    bnf: 'Backus–Naur form',
    brainfuck: 'Brainfuck',
    brightscript: 'BrightScript',
    bro: 'Bro',
    c: 'C',
    csharp: 'C#',
    cpp: 'C++',
    cil: 'CIL',
    coffeescript: 'CoffeeScript',
    cmake: 'CMake',
    clojure: 'Clojure',
    crystal: 'Crystal',
    csp: 'Content-Security-Policy',
    'css-extras': 'CSS Extras',
    d: 'D',
    dart: 'Dart',
    diff: 'Diff',
    django: 'Django/Jinja2',
    'dns-zone-file': 'DNS zone file',
    docker: 'Docker',
    ebnf: 'Extended Backus–Naur form',
    eiffel: 'Eiffel',
    ejs: 'EJS',
    elixir: 'Elixir',
    elm: 'Elm',
    etlua: 'Embedded Lua templating',
    erb: 'ERB',
    erlang: 'Erlang',
    fsharp: 'F#',
    'firestore-security-rules': 'Firestore security rules',
    flow: 'Flow',
    fortran: 'Fortran',
    ftl: 'FreeMarker Template Language',
    gcode: 'G-code',
    gdscript: 'GDScript',
    gedcom: 'GEDCOM',
    gherkin: 'Gherkin',
    git: 'Git',
    glsl: 'GLSL',
    gml: 'GameMaker Language',
    go: 'Go',
    graphql: 'GraphQL',
    groovy: 'Groovy',
    haml: 'Haml',
    handlebars: 'Handlebars',
    haskell: 'Haskell',
    haxe: 'Haxe',
    hcl: 'HCL',
    http: 'HTTP',
    hpkp: 'HTTP Public-Key-Pins',
    hsts: 'HTTP Strict-Transport-Security',
    ichigojam: 'IchigoJam',
    icon: 'Icon',
    inform7: 'Inform 7',
    ini: 'Ini',
    io: 'Io',
    j: 'J',
    java: 'Java',
    javadoc: 'JavaDoc',
    javadoclike: 'JavaDoc-like',
    javastacktrace: 'Java stack trace',
    jolie: 'Jolie',
    jq: 'JQ',
    jsdoc: 'JSDoc',
    'js-extras': 'JS Extras',
    'js-templates': 'JS Templates',
    json: 'JSON',
    jsonp: 'JSONP',
    json5: 'JSON5',
    julia: 'Julia',
    keyman: 'Keyman',
    kotlin: 'Kotlin',
    latex: 'LaTeX',
    latte: 'Latte',
    less: 'Less',
    lilypond: 'LilyPond',
    liquid: 'Liquid',
    lisp: 'Lisp',
    livescript: 'LiveScript',
    lolcode: 'LOLCODE',
    lua: 'Lua',
    makefile: 'Makefile',
    markdown: 'Markdown',
    'markup-templating': 'Markup templating',
    matlab: 'MATLAB',
    mel: 'MEL',
    mizar: 'Mizar',
    monkey: 'Monkey',
    moonscript: 'MoonScript',
    n1ql: 'N1QL',
    n4js: 'N4JS',
    'nand2tetris-hdl': 'Nand To Tetris HDL',
    nasm: 'NASM',
    neon: 'NEON',
    nginx: 'nginx',
    nim: 'Nim',
    nix: 'Nix',
    nsis: 'NSIS',
    objectivec: 'Objective-C',
    ocaml: 'OCaml',
    opencl: 'OpenCL',
    oz: 'Oz',
    parigp: 'PARI/GP',
    parser: 'Parser',
    pascal: 'Pascal',
    pascaligo: 'Pascaligo',
    pcaxis: 'PC-Axis',
    perl: 'Perl',
    php: 'PHP',
    phpdoc: 'PHPDoc',
    'php-extras': 'PHP Extras',
    plsql: 'PL/SQL',
    powershell: 'PowerShell',
    processing: 'Processing',
    prolog: 'Prolog',
    properties: '.properties',
    protobuf: 'Protocol Buffers',
    pug: 'Pug',
    puppet: 'Puppet',
    pure: 'Pure',
    python: 'Python',
    q: 'Q (kdb+ database)',
    qml: 'QML',
    qore: 'Qore',
    r: 'R',
    jsx: 'React JSX',
    tsx: 'React TSX',
    renpy: "Ren'py",
    reason: 'Reason',
    regex: 'Regex',
    rest: 'reST (reStructuredText)',
    rip: 'Rip',
    roboconf: 'Roboconf',
    robotframework: 'Robot Framework',
    ruby: 'Ruby',
    rust: 'Rust',
    sas: 'SAS',
    sass: 'Sass (Sass)',
    scss: 'Sass (Scss)',
    scala: 'Scala',
    scheme: 'Scheme',
    'shell-session': 'Shell session',
    smalltalk: 'Smalltalk',
    smarty: 'Smarty',
    solidity: 'Solidity (Ethereum)',
    soy: 'Soy (Closure Template)',
    sparql: 'SPARQL',
    'splunk-spl': 'Splunk SPL',
    sqf: 'SQF: Status Quo Function (Arma 3)',
    sql: 'SQL',
    stylus: 'Stylus',
    swift: 'Swift',
    tap: 'TAP',
    tcl: 'Tcl',
    textile: 'Textile',
    toml: 'TOML',
    tt2: 'Template Toolkit 2',
    turtle: 'Turtle',
    twig: 'Twig',
    typescript: 'TypeScript',
    't4-cs': 'T4 Text Templates (C#)',
    't4-vb': 'T4 Text Templates (VB)',
    't4-templating': 'T4 templating',
    vala: 'Vala',
    vbnet: 'VB.Net',
    velocity: 'Velocity',
    verilog: 'Verilog',
    vhdl: 'VHDL',
    vim: 'vim',
    'visual-basic': 'Visual Basic',
    wasm: 'WebAssembly',
    wiki: 'Wiki markup',
    xeora: 'Xeora',
    xojo: 'Xojo (REALbasic)',
    xquery: 'XQuery',
    yaml: 'YAML',
    zig: 'Zig'
};
